#!/usr/bin/env python
from __future__ import print_function
import sys
import nose
from env_importer import EnvImporter
def report_failed_plugin(path, e):
	print("Warning: couldn't import plugin %s - %s: %s" % (path, type(e).__name__, e), file=sys.stderr)
	return True

loader = EnvImporter(envvar='NOSETESTS_PLUGINS')
plugins = loader.load_all(on_error=report_failed_plugin)
nose.main(addplugins = plugins)
