#!/usr/bin/env python
import sys
import nose
from env_importer import EnvImporter
def report_failed_plugin(path, e):
	print >> sys.stderr, "Warning: couldn't import plugin %s - %s" % (path,e)

loader = EnvImporter(envvar='NOSETESTS_PLUGINS')
nose.main(addplugins = loader.load_all(on_error=report_failed_plugin))
